### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [drgrigg/anthony-trollope_the-last-chronicle-of-barset#1]
General Changes:
- [x] `se clean .` makes a few changes.

- [x] `se typogrify .` makes a change.

- [ ] The paragraphs with the `se:letter.dateline` semantic are missing `<time>` elements for the dates.

Chapter 4:
- [x] "De Arte Poetica" by Horace is not a book-length poem. It should be in quotes.

Chapter 13:
- [x] In the letter, the obscured year uses the wrong type of dash. It needs a regular hyphen.

Chapter 23:
- [x] In "General Committee Office, - January, 186-.", the dash between "Office" and "January" is the wrong type of dash. Other date lines use an em dash.

- [x]  I think the `<span epub:type="z3998:salutation">` should be inside of the left double quote (line 30).

Chapter 42:
- [x] The obscured day of the month should have a space instead of a word joiner before the em dash (line 91).

- [x] In the letter, the obscured year uses the wrong type of dash. It needs a regular hyphen.

Chapter 61:

- [x] In the letter, the obscured year uses the wrong type of dash. It needs a regular hyphen.

Chapter 62:

- [x] In the letter, the obscured year uses the wrong type of dash. It needs a regular hyphen.

Chapter 73:
- [x] At the end of the in-line letter, I think the closing  `</span>` for the letter needs to be outside of the right double quote (line 68).

Chapter 82:

- [x] In the letter, the obscured year uses the wrong type of dash. It needs a regular hyphen.

**Comment by drgrigg** [comment]
Thanks, Emma.

"The paragraphs with the se:letter.dateline semantic are missing <time> elements for the dates."

Well, I wasn't sure whether to put these in, since the date in _all_ cases has an obscured year and quite often also obscures the day of the month. Is it worth having a datetime element which just indicates the month with no year or day of month? I'm not sure they would even be valid tags. So for consistency I've left them all out. What do you think?

"the obscured year uses the wrong type of dash. It needs a regular hyphen."

I've fixed all these.

" In "General Committee Office, - January, 186-.", the dash between "Office" and "January" is the wrong type of dash. Other date lines use an em dash."

When I looked at this I realised that all of the datelines were problematic. I've rationalised all datelines now to use a comma and an em-dash if the day of month is obscured, which matches the page scans.

However, the trouble with this approach is that typogrify undoes all of this, removing commas and putting in word-joiner characters!  We might need to ask Alex what we should do here.

**Comment by EmmaSweeney** [comment]
My thought behind adding `<time>` elements around the obscured dates was so that the elements would stop `se typogrify .` from removing commas and adding word joiners before the dates.
```
				<header>
					<p epub:type="se:letter.dateline">The Palace, Barchester, <time>— December, 186-</time>.</p>
				</header>
```
Unfortunately, typogrify still removes the spaces between the dates and months. This would be easier to fix than without the `<time>` elements.
```
				<header>
					<p epub:type="se:letter.dateline">The Palace, Barchester, <time>—December, 186-</time>.</p>
				</header>
```

@acabal What would be the best solution for the obscured dates? Can we use an empty `<time>` tag if there isn't a valid `datetime` attribute?

**Comment by drgrigg** [comment]
@acabal The other issue here is that using a one-em dash for an obscured day of the month isn't covered in the manual, which says that a completely obscured "word" should be replaced with a three-em dash, which would look ridiculous in this context.

**Comment by acabal** [comment]
The manual has instructions for obscuring dates and years: https://standardebooks.org/manual/1.6.4/single-page#8.7.7.8

We don't necessarily want to add structure just to please typogrify. In many cases typogrify will make wrong choices even on correct text so it's not expected for it to run cleanly on any repo.

Whatever we do, it has to be valid HTML5. See the [definition of `<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) for an idea of what's required. The `datetime` attribute is not *required* but it has many possible formats that may work here.

**Comment by drgrigg** [comment]
The manual covers how to deal with partially obscured **years**, yes, but there’s no guidance I can see about how to deal with an obscured **day of the month** , which is the issue here. The guidance that a fully obscured word should be replaced with a three-em dash doesn’t fit this case well.

**Comment by drgrigg** [comment]
There are no valid datetime formats which cover dates with both unknown years and unknown day of the week.

**Comment by drgrigg** [comment]
Based on Alex’ response I think the solution is to do what I’ve done: restore the comma from the page scans and follow this with a space, a one-em dash to represent the missing day of the week, another space and then the month. And ignore typogrify, with a suitable comment in the production notes.

**Comment by drgrigg** [comment]
Emma: So if we accept what I've done regarding datelines, I believe I've now addressed all the issues you raised.

**Comment by EmmaSweeney** [comment]
Sounds good
